[site]
slug = "httk-store"
repository-url = "https://github.com/httk/httk-store"
main-branch = "main"
import-roots = ["httk/store", "httk/registry"]

[[internal-dependency]]
distribution = "httk-core"
slug = "httk-core"
repository-url = "https://github.com/httk/httk-core"
main-branch = "main"
